version: '2.1'
services:

    rt1:

        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        
        command: tcpdump -nSt icmp
        networks:
            - tnet2

            
            
            
    rt2:
        image: tema1:latest
        networks:
            - tnet2
        volumes:
            - .:/elocal
        tty: true
        
        command: ping -s 4000 rt1
        depends_on:
             - rt1

    rt3:
        command: ping rt1
        sysctls:
             - net.ipv4.icmp_echo_ignore_all=1
        depends_on:
             - rt1
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        

    rt4:
        depends_on:
             - rt3
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        command: ping -c 1 rt3
        
        networks:
            - tnet1
       

    tn1:
    
        command: bash -c 'echo \"- Interfata retea:\" && ip addr && echo \"- gateway:\" && ip route show'
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet1
        
        
        
 
networks:
     tnet1:
        ipam:
            driver: default
            config:
                - subnet: 11.153.209.253/30
                  gateway: 11.153.209.253 


     tnet2:
        ipam:
            driver: default
            config:
                - subnet: 1.2.0.0/17
                  ip_range: 1.2.3.0/27
                  gateway: 1.2.3.4

